<a href="https://colab.research.google.com/github/Priya-Saini-1/DataScience_Grras/blob/Python/Day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Welcome to Day 8***

**Array and list**

In [1]:
 import numpy as np
# from numpy import array

# list 1d
l = [1, 2, 3]
lm = l*2
print(lm)

# array 1d
arr = np.array(l)
print(arr)

# # 2-D list
# l = [[1, 2, 3],[4, 5, 6]]
# print(l)
# print(l[0]) # row 1
# print(l[1]) # row 2
# print(l[0][0]) # row 1, col 1
# print(l[0][1]) # row 1, col 2

# # 2-D array
# arr = np.array([[1, 2, 3] , [4, 5, 6]])
# print(arr)
# print(arr[0]) # row 1
# print(arr[1])

# # Replace 4 with 100
# arr[1][0] = 100
# print(arr)

[1, 2, 3, 1, 2, 3]
[1 2 3]


In [2]:
# comparision
#list
import time
start = time.time()
l = [i*2 for i in range(1000000)]
print("list output:", time.time() - start)

# array
import numpy as np

start = time.time()
arr = np.array(100000000) * 2
print("array output: ", time.time() - start)

list output: 0.0657663345336914
array output:  0.00013637542724609375


In [3]:
# time taken by list and array
import time

# List timing
start = time.time()

l = [i * 2 for i in range(1000000)]

end = time.time()
print("Time taken by list:", end - start)

# NumPy array timing
start = time.time()

a = np.array(1000000) * 2

end = time.time()
print("Time taken by array:", end - start)

Time taken by list: 0.08184075355529785
Time taken by array: 0.00015163421630859375


In [4]:
# zeros array 1d
import numpy as np
arr = np.zeros(5)
print(arr)

# zeroses array 2D
arr1 = np.zeros((3, 4))
print(arr1)

# ones array 1d
arr2 = np.ones(5)
print(arr2)

# ones array 2D
arr3 = np.ones((3, 4))
print(arr3)


[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
# full for 1d
import numpy as np
arr = np.full(3, 5)
print(arr)

# full for 2d
arr1 = np.full((3, 4), 5)
print(arr1)

[5 5 5]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [6]:

# question  with help of zeros make a 2d array having value 6
import numpy as np
arr=np.zeros((3,4))
arr= arr + 6
print(arr)


# question  with help of full make a 2d array having value
import numpy as np
arr1=np.full((2,3),1)
print(arr1)


[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]
[[1 1 1]
 [1 1 1]]


In [7]:
import numpy as np
arr = np.arange(6).reshape(2,3)
print(arr)

# arange 2d
import numpy as np
arr=np.arange(12).reshape(3,4)
print(arr)

[[0 1 2]
 [3 4 5]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
import numpy as np
# vector 1d list
l = [1,2,3]
print(l)
#vector 1d array
arr = np.array(l)
print(arr)

#matrix 2d list
l = [[1,2,3],[4,5,6]]
print(l)
#matrix 2d array
arr = np.array(l)
print(arr)

#tensor 3d list
l = [[[1,2],[3,4]],[[5,6],[7,8]]]
print(l)
#tensor 3d array
arr = np.array(l)
print(arr)

[1, 2, 3]
[1 2 3]
[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
#array
import numpy as np
arr = np.arange(11).reshape(11,1)
print("shape:",np.shape(arr))
print("dimension:", np.ndim(arr))
print("size:",np.size(arr))
print("data type:", arr.dtype)

shape: (11, 1)
dimension: 2
size: 11
data type: int64


In [22]:
# reshaping array
import numpy as np
arr = np.arange(12)
up_arr = np.reshape(arr, (3, 4))
print(up_arr)

# example 2d
arr = np.arange(24)
up_arr = np.reshape(arr, (12*2))
print(up_arr)

# example 3d
arr = np.arange(24)
up_arr = np.reshape(arr, (3*2*4))
print(up_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [23]:
# flatten : creates a copy
import numpy as np
arr = np.arange(12).reshape(3,4)
print(arr)
up_arr = arr.flatten()
print(up_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
# ravel : works on original
import numpy as np
#example 2d
arr = np.arange(14).reshape(7, 2)
up_arr = arr.ravel()
print(up_arr)

#example 3d
arr = np.arange(12).reshape(3, 2, 2)
up_arr = arr.ravel()
print(up_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [30]:
#transpose
# import numpy as np
# arr = np.array([[1,2,3], [4,5,6]])
# print(arr)
# print("transpose")
# print(arr.T)

# # transpose 3d
# import numpy as np
# arr=np.arange(24).reshape(2,3,4)
# print(arr)
# print("transpose")
# up_arr=arr.T
# print(up_arr)

 # slicing in 3d
import numpy as np
arr = np.arange(24).reshape(2,3,4)
print(arr)
print(arr[0:2,0:2,0:2])

import numpy as np
arr = np.arange(24).reshape(2,3,4)
print(arr)
print(arr[0:2,0:2,0:2])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1]
  [ 4  5]]

 [[12 13]
  [16 17]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1]
  [ 4  5]]

 [[12 13]
  [16 17]]]


In [31]:
# while loop for 3d
import numpy as np
arr = np.arange(24).reshape(2, 3, 4)


i = 0
while i < len(arr):
  j = 0
  while j < len(arr[i]):
    k = 0
    while k < len(arr[i][j]):
      print(arr[i][j][k], end=" ")
      k += 1
    print()
    j += 1
  print()
  i += 1

0 1 2 3 
4 5 6 7 
8 9 10 11 

12 13 14 15 
16 17 18 19 
20 21 22 23 



In [32]:
#for loop for 3d
import numpy as np
arr = np.arange(24).reshape(2, 3, 4)
for i in arr:
    for j in i:
        for k in j:
            print(k, end=" ")
        print()
    print()

0 1 2 3 
4 5 6 7 
8 9 10 11 

12 13 14 15 
16 17 18 19 
20 21 22 23 



In [33]:
import numpy as np
# for loop 1d array
arr2=np.arange(12)
for i in range(len(arr2)):
    print(arr2[i],end=" ")
print("\n")
# for loop 2d array
arr3=np.arange(12).reshape(3,4)
for i in range(len(arr3)):
    for j in range(len(arr3[i])):
        print(arr3[i][j],end=" ")
    print()
print("\n")
# for loop 3d array
arr4=np.arange(12).reshape(2,2,3)
# print(arr4)
for i in range(len(arr4)):
    print(f"layer {i}")
    for j in range(len(arr4[i])):
        for k in range(len(arr4[i][j])):
            print(arr4[i][j][k],end=" ")
        print()
    print()

0 1 2 3 4 5 6 7 8 9 10 11 

0 1 2 3 
4 5 6 7 
8 9 10 11 


layer 0
0 1 2 
3 4 5 

layer 1
6 7 8 
9 10 11 



**Extras**

In [11]:
# list functions

planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

# How many planets are there?
len(planets)

# The planets sorted in alphabetical order
sorted(planets)

primes = [2, 3, 5, 7]
sum(primes)

max(primes)
min(primes)

2

In [12]:
# interlude: objects

x = 12
# x is a real number, so its imaginary part is 0.
print(x.imag)
# Here's how to make a complex number, in case you've ever been curious:
c = 12 + 3j
print(c.imag)

0
3.0


https://claude.ai/share/f8dcdc85-3c77-42c0-a761-edec540e8daa